### ISSUE TITLE
ability of undefined error in advanceDeploy

### ISSUE THREAD

**Issue by Ayanrocks** [ethential/ethcode#164]
An error is occurring viz
```
cannot set property ability of undefined
```
this happens in line 144 of Deploy.tsx
```ts
methodArray[methodname].stateMutprops.ability = props.abi[i].stateMutability;

```
https://github.com/ethential/ethcode/blob/refactor_v2/src/components/Deploy/Deploy.tsx#L144

**Comment by Aniket6990** [comment]
this issue is fixed now, after v2 merge ethcode will use etherjs for abi creation
