### ISSUE TITLE
Error from IDE : Webview is disposed

### ISSUE THREAD

**Issue by 0mkara** [ethential/ethcode#178]
# Description
1. Activate Ethcode Remix Plugin
2. Compile
3. Load compiled result into Ethcode extension
4. Close Ethcode
5. Try to load compiled result from Remix plugin
6. Produces `Error: Webview is disposed`.
# Error message
```
Uncaught (in promise) Error: Error from IDE : Webview is disposed
```
![Screenshot from 2021-04-30 04-20-47](https://user-images.githubusercontent.com/13261372/116627863-8c937180-a96b-11eb-8291-27fda0a9e267.png)

**Comment by Aniket6990** [comment]
this issue is fixed now because now
