### ISSUE TITLE
Native features

### ISSUE THREAD

**Issue by 0mkara** [ethential/ethcode#192]
- [ ] select gas strategy
- [x] get account balance
- [ ] send ether value with transaction
- [ ] deploy bytecode
- [ ] call contract with ABI
- [ ] reload contracts on UI

**Comment by 0mkara** [comment]
- [ ] error message if list ethereum account fails

**Comment by 0mkara** [comment]
- [ ] use account selected for use in `workspaceState`

**Comment by Aniket6990** [comment]
this issue will be fixed after v2 merge of ethcode.
