### ISSUE TITLE
Load combined json displays an alert dialog

### ISSUE THREAD

**Issue by domin191013** [ethential/ethcode#217]
Load combined json not work on windows machine, and it's displaying an error dialog.

**Comment by domin191013** [comment]
Previous one wasn't loading either remix or hardhat version. Becuase there was difference in type of the input json.
So I've created HardhatJSONOutput interface and RemixJSONOutput and CombinedJSONOutput interface to store one of them in one interface.

There was 2 loading commands: load combined-json output, load standard-json output.
How about merging it into one -> load json output ?
And in that function, check if it's hardhat version or remix version.

Second issue is that, there's bin/bytecode in remix built version.
But it seems, abi and bin/bytecode is necessary to deploy the transaction or so.

**Comment by 0mkara** [comment]
#224
